export const DEFAULT_GITHUB_USERNAME = 'varunKT001';
export const DEFAULT_TEMPLATE_NAME = 'simple';
export const DEFAULT_FULL_NAME = 'Varun Kumar Tiwari';
export const DEFAULT_FIELDS_OF_WORK = [
  'Frontend Developer',
  'Backend Developer',
];
export const EMOJIS = [
  '⚽️',
  '🏀',
  '🏈',
  '⚾️',
  '🎾',
  '🏐',
  '🏉',
  '🎱',
  '🏓',
  '🏸',
  '🥅',
  '🏒',
  '🏑',
  '🏏',
  '⛳️',
  '🏹',
  '🎣',
  '🥊',
  '🥋',
  '⛸',
  '🎿',
  '⛷',
  '🏂',
  '🏋️‍♀️',
  '🏋',
  '🤺',
  '🤼‍♀',
  '🤼‍♂',
  '🤸‍♀',
  '🤸‍♂',
  '⛹️‍♀️',
  '⛹',
  '🤾‍♀',
  '🤾‍♂',
  '🏌️‍♀️',
  '🏌',
  '🏄‍♀',
  '🏄',
  '🏊‍♀',
  '🏊',
  '🤽‍♀',
  '🤽‍♂',
  '🚣‍♀',
  '🚣',
  '🏇',
  '🚴‍♀',
  '🚴',
  '🚵‍♀',
  '🚵',
  '🎽',
  '🏅',
  '🎖',
  '🥇',
  '🥈',
  '🥉',
  '🏆',
  '🏵',
  '🎗',
  '🎫',
  '🎟',
  '🎪',
  '🤹‍♀',
  '🤹‍♂',
  '🎭',
  '🎨',
  '🎬',
  '🎤',
  '🎧',
  '🎼',
  '🎹',
  '🥁',
  '🎷',
  '🎺',
  '🎸',
  '🎻',
  '🎲',
  '🎯',
  '🎳',
  '🎮',
  '🎰',
];
export const DEFAULT_ABOUT_ME = [
  {
    title: `I'm currently learning`,
    emoji: EMOJIS[Math.floor(Math.random() * EMOJIS.length)],
    name: `Typescript`,
    link: '',
  },
  {
    title: ` I'm looking for`,
    emoji: EMOJIS[Math.floor(Math.random() * EMOJIS.length)],
    name: `open-source/internship opportunities`,
    link: '',
  },
  {
    title: `Find all my projects at`,
    emoji: EMOJIS[Math.floor(Math.random() * EMOJIS.length)],
    name: `varuntiwari.xyz`,
    link: `https://varuntiwari.xyz`,
  },
  {
    title: `How to reach me`,
    emoji: EMOJIS[Math.floor(Math.random() * EMOJIS.length)],
    name: `tiwarivarun819.vt33.vt@gmail.com`,
    link: `tiwarivarun819.vt33.vt@gmail.com`,
  },
];
export const DEFAULT_ACHIEVEMENTS = [
  {
    title: `Winner of OpenCode'21, one of the biggest open-source events, organized by GeekHaven, IIITA.`,
    link: `https://www.linkedin.com/posts/geekhaven-iiita_opencode21-witnessed-extensive-participation-activity-6866010351947825152-KiNB/`,
  },
  {
    title: `Finished in the Top 10 in Out of Context, an event organized by Effervescence, IIITA.`,
    link: `https://www.linkedin.com/posts/varun-tiwari-454591178_top10-outofcontext-design-activity-6882312778040930304-Fshh`,
  },
  {
    title: `GSSOC'22 Project Admin, with my project Tomper Wear E-commerce.`,
    link: `https://www.linkedin.com/posts/varun-tiwari-454591178_gssoc22-girlscript-educationfirst-activity-6903552524234686464-bEEL`,
  },
  {
    title: `TomperWear e-commerce awarded as the Best Web App in Winter Projects organized by GDSC and AASF, IIITM, Gwalior.`,
    link: `https://www.linkedin.com/posts/aasf-iiitmg_github-winterprojects-learning-activity-6909474506340282368-GYq5`,
  },
];
export const DEFAULT_SKILLS = [
  {
    skill: 'JavaScript',
    url: 'https://img.shields.io/badge/javascript-%23323330.svg?style=for-the-badge&logo=javascript&logoColor=%23F7DF1E',
  },
  {
    skill: 'TypeScript',
    url: 'https://img.shields.io/badge/typescript-%23007ACC.svg?style=for-the-badge&logo=typescript&logoColor=white',
  },
];
export const DEFAULT_STATS = {
  show: true,
  options: {
    streaks: {
      show: true,
      theme: 'default',
    },
    contributions: {
      show: true,
      theme: 'default',
    },
  },
};
